version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    target-branch: "develop"
    labels:
      - "Technical Debt"
    schedule:
      interval: weekly
      time: "05:00"
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      npm-all:
        patterns:
          - "*"
  # Fetch and update latest `github-actions` packages
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "05:00"
    target-branch: "develop"
    labels:
      - "Technical Debt"
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      github-actions-all:
        patterns:
          - "*"
